### PR TITLE
Spanish translation, 1st draft

### PR DESCRIPTION
**Pull request by jarxg**

### CODE REVIEW

**Comment by lvm** [comment]
Hi there,

I'm not sure with the translation "interpretación" for "performance/acts", I'd go with "performance". Mainly because most people participating don't have a partiture to play. See below too. Line 8. 
Same thing with "programar al vuelo" for "live coded". Line 8.
I'd just leave "actos principales" and remove "headliners". Or vice versa. Line 14.
In Line 17, "...sólo estamos probando hacer cosas distintas dentro de una historia..." i'd go with just "...solo estamos probando cosas dentro de una historia..." since it doesn't says (explicitly) "different" anywhere.
And for Line 29, same thing here with "intérpretes y organizadores" for "performers and event organizers". 

Why i insist with the word "intérprete"? Because it might give the impresion that a person participating is a musician and this might not always be the case. 
 
Just my 2 cents.

Other than that, it's fantastic.

Saludos,
Mauro

**Comment by jarxg** [comment]
Yeah, I had my doubts with "intérprete" and all your other examples.
Changing it now, thanks, Mauro!

**Comment by yaxu** [comment]
Great! Is this ready to merge?

**Comment by munshkr** [comment]
Awesome! I also agree with lvm's comments.

The gender of the word [performance](http://dle.rae.es/?id=SbFtbrL) is feminine, so in line 8 it would better to say "La mayoría de ~los~las performances". Beside that, looks good to me.

**Pull request merged**
